### PR TITLE
Added new images

### LINKED ISSUE #34: optimize images
many of the site images are not scaled right

### PR DESCRIPTION
**Pull request by dorsha**
Resolve #34

### CODE REVIEW

**Comment by orius123** [comment]
1. I don't like the new images..
2. We can optimize them more before merging.

**Comment by dorsha** [comment]
1. Shay/Asi. In addition, the fiverr images will be first
2. Asi already optimized them, this is the size that they want, so optimizing and keeping them in the same size will reduce the quality and it won't look good

**Comment by meirwah** [comment]
:-1: on this... all images look worse then before.... 
better to keep the website as is..

**Comment by oritstone** [comment]
:-1: as well

**Comment by dorsha** [comment]
I think we should use the fiverr images only (the cartoons) and not the real images. the current images look bad as well, small resolutions, crowded and not neat.

**Comment by SamMarkowitz** [comment]
Now includes fixes to #41, #43 and score-language/#59

**Comment by meirwah** [comment]
seem to have conflicts on this pull request...

**Comment by SamMarkowitz** [comment]
Added a section on Slang architecture. @orius123 or @oritstone, please review and let me know what is incorrect, incomplete, etc.

**Comment by SamMarkowitz** [comment]
Added score architecture section. @orius123 please review.

**Comment by meirwah** [comment]
why everything is on the same branch?

**Comment by SamMarkowitz** [comment]
I've been using the development branch because it builds to the development site and then I can see that everything is laying out properly.

**Pull request closed without merging**
