### PR TITLE
Added blog for review

### PR DESCRIPTION
**Pull request by dorsha**

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
Added my changes to the SLANG DSL Reference section. Please review.

**Comment by orius123** [comment]
Hi, Sam.
Awesome job with SLANG docs, I really like it.
the only thing i would suggest is to group related bullets together, i.e. all of the inputs properties (required, override...)

hopefully will merge tomorrow, you can see it already at http://openscoredev.herokuapp.com/#/docs

**Comment by dorsha** [comment]
Fixed the navigation icon problem

**Comment by SamMarkowitz** [comment]
@orius123 - I thought about a few ways to organize the DSL Reference. 

Originally I wanted to structure it hierarchically, in the way the concepts show up in a flow, etc. but it lead to a couple of problems:
  - Too many heading levels (although all of them could be placed at the same level, it would lose some of the structure idea to do so.)
  - What to do with properties that show up in more than one place (e.g. inputs go in a flow and an operation)
  - Difficulty in quickly locating a single concept.

Instead I decided on the alphabetical listing with the two hierarchic outlines of flows and operations at the top. (Currently these are incomplete, missing some of the detailed parameters, but I think I will fill everything in.) I also added **a lot** of links to ease the process of going from one idea to its related concepts.

I think what you propose is something in between the two approaches above. I'm not sure where you draw the line about what goes with its parent concept (`default` with `inputs` yes?) and what doesn't (`inputs` with `flow` no?).

**Pull request merged**
